name: wg-web-app
services:
  wg-web-app:
    container_name: wg-web-app
    image: ghcr.io/xel1nax/wg-web-app:latest
    environment:
      - WG_APP_HOST=0.0.0.0
      - WG_APP_PORT=5000
      - WG_ACTIVE_CONFIG_PATH=/etc/wireguard/wg0.conf
      - WG_PRESET_DIR=/app/configs
      - WG_BACKUP_DIR=/app/backups
      - WG_RESTART_COMMAND=/usr/local/bin/restart-wireguard
      - WG_SYSTEMD_UNIT=wg-quick@wg0
    ports:
      - target: 5000
        published: "${WG_APP_PORT_HOST:-5000}"
        protocol: tcp
    pid: host
    privileged: true
    volumes:
      - type: bind
        source: /etc/wireguard
        target: /etc/wireguard
      - type: bind
        source: ./configs
        target: /app/configs
      - type: bind
        source: ./backups
        target: /app/backups
    restart: unless-stopped
